# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormView.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(900, 556)
        self.gridLayout = QtWidgets.QGridLayout(dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.infoLabel = QtWidgets.QLabel(dialog)
        self.infoLabel.setMaximumSize(QtCore.QSize(802, 16777215))
        self.infoLabel.setWordWrap(True)
        self.infoLabel.setObjectName("infoLabel")
        self.gridLayout.addWidget(self.infoLabel, 4, 0, 1, 6)
        self.label = QtWidgets.QLabel(dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.batchDownloadButton = QtWidgets.QPushButton(dialog)
        self.batchDownloadButton.setMinimumSize(QtCore.QSize(0, 30))
        self.batchDownloadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.batchDownloadButton.setObjectName("batchDownloadButton")
        self.gridLayout.addWidget(self.batchDownloadButton, 1, 5, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(dialog)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 5, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(dialog)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(dialog)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.downloadTaskNumEdit = QtWidgets.QLineEdit(dialog)
        self.downloadTaskNumEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.downloadTaskNumEdit.setObjectName("downloadTaskNumEdit")
        self.gridLayout.addWidget(self.downloadTaskNumEdit, 1, 3, 1, 1)
        self.tableView = QtWidgets.QTableView(dialog)
        self.tableView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setShowGrid(True)
        self.tableView.setGridStyle(QtCore.Qt.SolidLine)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setCascadingSectionResizes(True)
        self.tableView.horizontalHeader().setSortIndicatorShown(True)
        self.tableView.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.tableView, 3, 0, 1, 6)
        self.savePathEdit = QtWidgets.QLineEdit(dialog)
        self.savePathEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.savePathEdit.setObjectName("savePathEdit")
        self.gridLayout.addWidget(self.savePathEdit, 2, 1, 1, 3)
        self.proxyPathEdit = QtWidgets.QLineEdit(dialog)
        self.proxyPathEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.proxyPathEdit.setObjectName("proxyPathEdit")
        self.gridLayout.addWidget(self.proxyPathEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(dialog)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 4)

        self.retranslateUi(dialog)
        self.pushButton.clicked.connect(dialog.parsing_btn_click)
        self.batchDownloadButton.clicked.connect(dialog.batch_download_btn_click)
        self.pushButton_3.clicked.connect(dialog.single_download_btn_click)
        self.pushButton_4.clicked.connect(dialog.select_file_dir_btn)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "页面解析"))
        self.infoLabel.setText(_translate("dialog", "等待"))
        self.label.setText(_translate("dialog", "列表地址"))
        self.batchDownloadButton.setText(_translate("dialog", "批量下载"))
        self.pushButton_3.setText(_translate("dialog", "下载单个"))
        self.pushButton_4.setText(_translate("dialog", "选择位置"))
        self.pushButton.setText(_translate("dialog", "解析"))
        self.label_2.setText(_translate("dialog", "代理地址"))
        self.label_3.setText(_translate("dialog", "同时下载任务数"))
        self.label_4.setText(_translate("dialog", "存储位置"))
import res_rc
